// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// MetropolisCpp
List MetropolisCpp(double sigma, double x0, int N);
RcppExport SEXP _StatComp20065_MetropolisCpp(SEXP sigmaSEXP, SEXP x0SEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(MetropolisCpp(sigma, x0, N));
    return rcpp_result_gen;
END_RCPP
}
// Gradmat_cpp
NumericMatrix Gradmat_cpp(NumericVector parvec, Rcpp::Function infcn, double eps);
RcppExport SEXP _StatComp20065_Gradmat_cpp(SEXP parvecSEXP, SEXP infcnSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type parvec(parvecSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type infcn(infcnSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(Gradmat_cpp(parvec, infcn, eps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StatComp20065_MetropolisCpp", (DL_FUNC) &_StatComp20065_MetropolisCpp, 3},
    {"_StatComp20065_Gradmat_cpp", (DL_FUNC) &_StatComp20065_Gradmat_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_StatComp20065(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
